backend:
  name: git-gateway
  branch: master

site_url: https://esp-safety.netlify.com
public_url: https://esp-safety.netlify.com
logo_url: https://esp-safety.netlify.com/media/logo.svg
media_folder: static/media
public_folder: media

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "src/pages/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredPost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page" }
          - { label: Header, name: header, widget: object, fields: [
              { label: Title, name: title, widget: string },
              { label: Subtitle, name: subtitle, widget: text },
              { label: "Primary Button", name: 'primaryButton', widget: object, fields: [
                { label: "Label", name: "label", widget: string, default: '', required: true },
                { label: "Path", name: "path", widget: string, default: '', required: true },
                { label: "Open In New Window", name: "newWindow", widget: "boolean", default: false, required: false },
              ] },
              { label: "Secondary Button", name: 'secondaryButton', widget: object, fields: [
                { label: "Label", name: "label", widget: string, default: '', required: true },
                { label: "Path", name: "path", widget: string, default: '', required: true },
                { label: "Open In New Window", name: "newWindow", widget: "boolean", required: false }
              ] },
              { label: Background Video, name: backgroundVideo, widget: object, fields: [
                { label: MP4, name: mp4, widget: file, required: false },
                { label: WebM, name: webm, widget: file, required: false }
              ] },
              { label: Background Image, name: backgroundImage, widget: image, required: true },
              { label: Logos, label_singular: "Logo", name: logos, widget: list, fields: [
                { label: "Name", name: "name", required: true },
                { label: "Image", name: "image", required: true },
                { label: "URL", name: "url", required: true }
              ] }
            ] }
          - { label: Main Pitch, name: mainPitch, widget: object, fields: [
              { label: Supertitle, name: supertitle, widget: string },
              { label: Title, name: title, widget: string },
              { label: Description, name: description, widget: text }
            ] }
          - { label: "Product Categories", label_singular: "Product Category", name: productCategories, widget: list, fields: [
              { label: Product Category, name: productCategory, widget: relation, collection: "productCategories", searchFields: ["title"], valueField: "slug", displayFields: ["title"] },
              { label: Description, name: description, widget: text }
            ] }
          - { label: Detectors, name: detectors, widget: object, fields: [
              { label: Supertitle, name: supertitle, widget: string },
              { label: Title, name: title, widget: string },
              { label: Description, name: description, widget: text },
              { label: "Link", name: 'link', widget: object, fields: [
                { label: "Label", name: "label", widget: string, default: '', required: false },
                { label: "Path", name: "path", widget: string, default: '', required: false },
                { label: "Open In New Window", name: "newWindow", widget: "boolean", required: false }
              ] }
            ] }
          - { label: Certifications, name: certifications, widget: object, fields: [
              { label: Supertitle, name: supertitle, widget: string },
              { label: Title, name: title, widget: string },
              { label: Description, name: description, widget: markdown },
              { label: Logos, label_singular: "Logo", name: logos, widget: list, fields: [
                { label: "Name", name: "name", required: true },
                { label: "Image", name: "image", required: true },
                { label: "URL", name: "url", default: '', required: false }
              ] }
              { label: "Link", name: 'link', widget: object, fields: [
                { label: "Label", name: "label", widget: string, default: '', required: false },
                { label: "Path", name: "path", widget: string, default: '', required: false },
                { label: "Open In New Window", name: "newWindow", widget: "boolean", default: false, required: false }
              ] }
            ] }
          - { label: Convenience, name: convenience, widget: object, fields: [
              { label: Supertitle, name: supertitle, widget: string },
              { label: Title, name: title, widget: string },
              { label: Description, name: description, widget: markdown },
              { label: "Link", name: 'link', widget: object, fields: [
                { label: "Label", name: "label", widget: string, default: '', required: false },
                { label: "Path", name: "path", widget: string, default: '', required: false },
                { label: "Open In New Window", name: "newWindow", widget: "boolean", default: false, required: false }
              ] }
            ] }
          - { label: Customer Service, name: customerService, widget: object, fields: [
              { label: Supertitle, name: supertitle, widget: string },
              { label: Title, name: title, widget: string },
              { label: Description, name: description, widget: markdown },
              { label: "Link", name: 'link', widget: object, fields: [
                { label: "Label", name: "label", widget: string, default: '', required: false },
                { label: "Path", name: "path", widget: string, default: '', required: false },
                { label: "Open In New Window", name: "newWindow", default: false, widget: "boolean", required: false }
              ] }
            ] }
          - { label: Statistics, name: statustics, widget: list, fields: [
              { label: Number, name: number, widget: string, required: true },
              { label: Unit, name: unit, widget: string, required: false },
              { label: Label, name: label, widget: string, required: true }
            ] }
          - { label: Customer Testimonials, name: customerTestimonials, widget: object, fields: [
              { label: Supertitle, name: supertitle, widget: string },
              { label: Title, name: title, widget: string },
              { label: Testimonials, name: testimonials, widget: list, fields: [
                { label: Quote, name: quote, widget: text, required: true },
                { label: Author, name: author, widget: object, fields: [
                  { label: Name, name: name, widget: string, required: true },
                  { label: Title, name: title, widget: string, required: false },
                  { label: Company, name: company, widget: string, required: false },
                  { label: Image, name: image, widget: image, required: false, default: /media/avatar-placeholder.png }
                ] },
              ] }
            ] }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "products"
    label: "Products"
    label_singular: "Product"
    folder: "src/pages/products"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "product" }
      - { label: "Slug", name: "slug", required: true, pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Cannot contain spaces, capital letters, or special characters. You may separate words with dashes and numbers are allowed."], hint: "This will be used in the URL." }
      - { label: "Category", name: "category", widget: "relation", collection: "productCategories", searchFields: ["title"], valueField: "slug", displayFields: ["title"] }
      - { label: "Product Name", name: "title" }
      - { label: "Subtitle", name: "subtitle" }
      - { label: "Highlight", name: "highlight" }
      - { label: "Images", name: "images", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
      - { label: "Summary", name: "summary", widget: "markdown" }
      - { label: "Model", name: "model", required: false }
      - { label: "Function", name: "function", required: false }
      - { label: "Rating", name: "rating", required: false }
      - { label: "Overview", name: "overview", widget: "markdown", required: false }
      - { label: "Sections", label_singular: "Section", name: "sections", widget: "list", fields: [
          { label: "Image", name: "image", widget: "image" },
          { label: "Supertitle", name: "supertitle", widget: "string", required: false },
          { label: "Title", name: "title", widget: "string", required: false },
          { label: "Content", name: "content", widget: "markdown" },
          { label: "Link", name: "link", widget: "object", required: false, fields: [
            { label: "Text", name: "text", widget: "string", required: false },
            { label: "URL", name: "url", widget: "string", required: false },
            { label: "Open In New Window", name: "newWindow", widget: "boolean", required: false }
          ]}
        ]}
      - { label: "Applications", label_singular: "Application", name: "applications", widget: "list", fields: [{label: "Application", name: "application", widget: "string"}] }
      - { label: "Features", label_singular: "Feature", name: "features", widget: "list", fields: [{label: "Feature", name: "feature", widget: "string"}] }
      - { label: "Specification Categories", name: "specificationCategories", widget: "list", fields: [
            { label: "Title", name: "title", widget: "string", required: true },
            # { label: "Layout", name: "layout", widget: "select", options: [{ label: "Rows", value: "rows" }, { label: "Columns", value: "columns" }] },
            { label: "Specifications", name: "specifications", widget: "list", required: true, fields: [
              { label: "Label", name: "label", widget: "string", required: false },
              # { label: "Label Position", name: "labelPosition", widget: "select", options: [
              #   { label: "Top", value: "top" },
              #   { label: "Left", value: "left" }
              # ]},
              { label: "Text", name: "text", widget: "markdown", required: false },
              { label: "Image",  name: "image", required: false},
              # { label: "Image Position", name: "imagePosition", widget: "select", required: false, options: [
              #   { label: "Top", value: "top" },
              #   { label: "Left", value: "left" }
              # ]},
              { label: "Link", name: "link", widget: "object", required: false, fields: [
                { label: "Text", name: "text", widget: "string", required: false },
                { label: "URL", name: "url", widget: "string", required: false },
                { label: "Open In New Window", name: "newWindow", widget: "boolean", required: false }
              ]},
              { label: "Disclaimer",name: "disclaimer", widget: "text", required: false },
              { label: "Full-width", name: "fullWidth", widget: "boolean", required: false }
            ]}
          ]
        }
      - { label: "Download Categories", label_singular: "Download Category", name: "downloadCategories", widget: "list", fields: [
          { label: "Title", name: "title", widget: "string" },
          { label: "Downloads", label_singular: "Download", name: "downloads", widget: "list", fields: [
            { label: "File", name: "file", widget: "file" },
            { label: "Title", name: "title", widget: "string" },
            { label: "Description", name: "description", widget: "string" }
          ]}
        ]}
      - { label: "Accessories", name: "accessories", widget: "relation", collection: "products", searchFields: ["title"], valueField: "slug", displayFields: ["title"], multiple: true, required: false }
      - { label: "Related Products", name: "relatedProducts", widget: "relation", collection: "products", searchFields: ["title"], valueField: "slug", displayFields: ["title"], multiple: true, required: false }

  - name: "productCategories"
    label: "Product Categories"
    label_singular: "Product Category"
    folder: "src/pages/product-categories"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "product-category" }
      - { label: "Product Category Name", name: "title" }
      - { label: "Slug", name: "slug", required: true, pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Cannot contain spaces, capital letters, or special characters. You may separate words with dashes and numbers are allowed."], hint: "This will be used in the URL." }
      - { label: "Icon", name: "icon", widget: "image", required: false }

  - name: "settings"
    label: "Settings"
    label_singular: "Setting"
    files:
      - file: "src/data/settings/navigation.yml"
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: navigation
            widget: object
            fields:
              - { label: "Links", label_singular: "Link", name: "links", widget: "list", fields: [
                  { label: "Label", name: "label", widget: string, required: false },
                  { label: "Path", name: "path", widget: string, required: false },
                  { label: "Open In New Window", name: "newWindow", widget: "boolean", required: false },
                  { label: "Links", label_singular: "Link", name: "links", widget: "list", fields: [
                    { label: "Label", name: "label", widget: string, required: false },
                    { label: "Path", name: "path", widget: string, required: false },
                    { label: "Open In New Window", name: "newWindow", widget: "boolean", required: false },
                    { label: "Links", label_singular: "Link", name: "links", widget: "list", fields: [
                      { label: "Label", name: "label", widget: string, required: false },
                      { label: "Path", name: "path", widget: string, required: false },
                      { label: "Open In New Window", name: "newWindow", widget: "boolean", required: false }
                    ]}
                  ]}
                ]}
      - file: "src/data/settings/footer.yml"
        label: Footer
        name: footer
        fields:
          - label: Footer
            name: footer
            widget: object
            fields:
              - { label: "Links", label_singular: "Link", name: "links", widget: "list", fields: [
                  { label: "Label", name: "label", widget: string, required: false },
                  { label: "Path", name: "path", widget: string, required: false },
                  { label: "Open In New Window", name: "newWindow", widget: "boolean", required: false }
                ]}
      - file: "src/data/settings/social-media.yml"
        label: "Social Media"
        name: social-media
        fields:
          - label: "Social Media"
            name: social-media
            widget: object
            fields:
              - { label: "Links", label_singular: "Link", name: "links", widget: "list", fields: [
                  { label: "Type", name: "type", widget: "select", options: [
                    { label: "Facebook", value: "facebook" },
                    { label: "Instagram", value: "instagram" },
                    { label: "LinkedIn", value: "linkedin" },
                    { label: "Pinterest", value: "pinterest" },
                    { label: "Tumblr", value: "tumblr" },
                    { label: "Twitter", value: "twitter" },
                    { label: "YouTube", value: "youtube" }
                  ]},
                  { label: "URL", name: "url", widget: string, required: false }
                ]}
